/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ooae2test1;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.TableModel;

public class FormInmateManager extends javax.swing.JFrame {

    prisonInmate pI;
//    wardenMethods wM;

    public FormInmateManager() throws SQLException {
        initComponents();
        pI = new prisonInmate();
//        this.wM = wardenActs;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fNameBox = new javax.swing.JTextField();
        lNameBox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        addInmateBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        closeBtn = new javax.swing.JButton();
        removeInmateBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        inmateTable = new javax.swing.JTable();
        refreshBtn = new javax.swing.JButton();
        updateRecordBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        uNameBox = new javax.swing.JTextField();
        PBox = new javax.swing.JTextField();
        assignTaskBtn = new javax.swing.JButton();
        assignPunishBtn = new javax.swing.JButton();
        removePrisonerBtn = new javax.swing.JButton();
        cellBlockChoice = new javax.swing.JComboBox();
        genderCombo = new javax.swing.JComboBox();
        statusCombo = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("First Name");

        jLabel2.setText("Last Name");

        jLabel3.setText("Gender");

        addInmateBtn.setText("Add Inmate");
        addInmateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addInmateBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Manage Inmates Form");

        jLabel5.setText("Cell Block");

        jLabel6.setText("Status");

        closeBtn.setText("Close");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        removeInmateBtn.setText("Remove Inmate");
        removeInmateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeInmateBtnActionPerformed(evt);
            }
        });

        inmateTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "Gender", "Cell Block", "Status", "Username", "Password"
            }
        ));
        inmateTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inmateTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(inmateTable);

        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        updateRecordBtn.setText("Update Record");
        updateRecordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateRecordBtnActionPerformed(evt);
            }
        });

        jLabel7.setText("Username");

        jLabel8.setText("Password");

        assignTaskBtn.setText("Assign Task");
        assignTaskBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignTaskBtnActionPerformed(evt);
            }
        });

        assignPunishBtn.setText("Assign Punishment");
        assignPunishBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignPunishBtnActionPerformed(evt);
            }
        });

        removePrisonerBtn.setText("Authorize Removal");
        removePrisonerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removePrisonerBtnActionPerformed(evt);
            }
        });

        cellBlockChoice.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A1", "A2", "A3", "B1", "B2", "B3", "C1", "C2", "C3" }));

        genderCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        statusCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Remand", "Death Row", "Lifetime", "Normal", "Long Term" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(assignTaskBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(assignPunishBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removePrisonerBtn)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cellBlockChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(statusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(genderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(uNameBox, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                .addComponent(lNameBox, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fNameBox, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(PBox, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addInmateBtn)
                        .addGap(18, 18, 18)
                        .addComponent(removeInmateBtn)
                        .addGap(18, 18, 18)
                        .addComponent(updateRecordBtn)
                        .addGap(18, 18, 18)
                        .addComponent(closeBtn)
                        .addGap(18, 18, 18)
                        .addComponent(refreshBtn)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(fNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(genderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cellBlockChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(statusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(uNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(PBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(assignTaskBtn)
                            .addComponent(assignPunishBtn)
                            .addComponent(removePrisonerBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addInmateBtn)
                    .addComponent(removeInmateBtn)
                    .addComponent(updateRecordBtn)
                    .addComponent(closeBtn)
                    .addComponent(refreshBtn))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void addInmateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addInmateBtnActionPerformed
        try {

            String fName = fNameBox.getText();
            String lName = lNameBox.getText();
            String gender = (String) genderCombo.getSelectedItem();
            String cellBlock = (String) cellBlockChoice.getSelectedItem();
            String inmateStatus = (String) statusCombo.getSelectedItem();
            String uName = uNameBox.getText();
            String pWord = PBox.getText();
            prisonInmate inmate = new prisonInmate(fName, lName, gender, cellBlock, inmateStatus, uName, pWord);

            boolean success = pI.addNewInmate(inmate);

            if (success) {
                popupMessage.infoBox("A new inmate has been successfully added to the system", "Information");
            }
            pI.populateInmatesTable(this);
        } catch (SQLException ex) {
            Logger.getLogger(FormInmateManager.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_addInmateBtnActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        try {

            pI.populateInmatesTable(this);
        } catch (SQLException ex) {
            Logger.getLogger(FormInmateManager.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_refreshBtnActionPerformed


    private void inmateTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inmateTableMouseClicked
        int i = inmateTable.getSelectedRow();

        TableModel model = inmateTable.getModel();

        // Display Selected Row In JTexteFields
        fNameBox.setText(model.getValueAt(i, 0).toString());

        lNameBox.setText(model.getValueAt(i, 1).toString());

        genderCombo.getModel().setSelectedItem(model.getValueAt(i, 2).toString());

        cellBlockChoice.getModel().setSelectedItem(model.getValueAt(i, 3).toString()); //https://stackoverflow.com/questions/8327352/how-to-set-selected-index-jcombobox-by-value

//        cellBlockBox.setText(model.getValueAt(i, 3).toString());
        statusCombo.getModel().setSelectedItem(model.getValueAt(i, 4).toString());

        uNameBox.setText(model.getValueAt(i, 5).toString());

        PBox.setText("*****");

    }//GEN-LAST:event_inmateTableMouseClicked

    private void removeInmateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeInmateBtnActionPerformed

        try {
            pI.removeInmate(uNameBox.getText(), this);
            pI.populateInmatesTable(this);
        } catch (SQLException ex) {
            Logger.getLogger(FormInmateManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_removeInmateBtnActionPerformed

    private void updateRecordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateRecordBtnActionPerformed
        try {

            String query = "UPDATE inmates SET cellBlock='" + 
                    (String) cellBlockChoice.getSelectedItem() + "',inmateStatus='"
                    + (String) statusCombo.getSelectedItem() + "' WHERE username = '"
                    + uNameBox.getText() + "'";
            https://www.dreamincode.net/forums/topic/144921-sql-update-query-in-java-netbeans/
            pI.executeSQlQuery(query, "Updated", this);
            pI.populateInmatesTable(this);
        } catch (SQLException ex) {
            Logger.getLogger(FormInmateManager.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_updateRecordBtnActionPerformed

    private void assignTaskBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignTaskBtnActionPerformed
        try {
            int i = inmateTable.getSelectedRow();
            TableModel model = inmateTable.getModel();
            String username = (model.getValueAt(i, 5).toString());
            FormInmateTask iT = new FormInmateTask(username);
            iT.setVisible(true);
            pI.populateInmatesTasksTable(iT);
        } catch (SQLException ex) {
            Logger.getLogger(FormGuardManager.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_assignTaskBtnActionPerformed
    public void accessRefresh(java.awt.event.ActionEvent evt) {
        refreshBtnActionPerformed(evt);
    }

    private void assignPunishBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignPunishBtnActionPerformed

        try {
            int i = inmateTable.getSelectedRow();
            TableModel model = inmateTable.getModel();

            String username = (model.getValueAt(i, 5).toString());

            FormInmatePunishment iP = new FormInmatePunishment(username);
            iP.setVisible(true);
            pI.populateInmatesPunishmentsTable(iP);
        } catch (SQLException ex) {
            Logger.getLogger(FormInmateManager.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_assignPunishBtnActionPerformed

    private void removePrisonerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removePrisonerBtnActionPerformed

        int i = inmateTable.getSelectedRow();

        TableModel model = inmateTable.getModel();

        String uName = (model.getValueAt(i, 5).toString());

        FormInmateRemoval iR = new FormInmateRemoval(uName, this);

        iR.setVisible(true);

    }//GEN-LAST:event_removePrisonerBtnActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) throws SQLException {
//
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FormInmateManager.class
//                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FormInmateManager.class
//                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FormInmateManager.class
//                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FormInmateManager.class
//                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//
//                try {
//                    new FormInmateManager().setVisible(true);
//
//                } catch (SQLException ex) {
//                    Logger.getLogger(FormInmateManager.class
//                            .getName()).log(Level.SEVERE, null, ex);
//                }
//
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PBox;
    private javax.swing.JButton addInmateBtn;
    private javax.swing.JButton assignPunishBtn;
    private javax.swing.JButton assignTaskBtn;
    private javax.swing.JComboBox cellBlockChoice;
    private javax.swing.JButton closeBtn;
    private javax.swing.JTextField fNameBox;
    private javax.swing.JComboBox genderCombo;
    protected javax.swing.JTable inmateTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lNameBox;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton removeInmateBtn;
    private javax.swing.JButton removePrisonerBtn;
    private javax.swing.JComboBox statusCombo;
    private javax.swing.JTextField uNameBox;
    private javax.swing.JButton updateRecordBtn;
    // End of variables declaration//GEN-END:variables
}
