/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ooae2test1;

import AbstractTaskFactory.Assignment;
import AbstractTaskFactory.assignmentFactory;
import AbstractTaskFactory.assignmentFactoryProducer;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.TableModel;

/**
 *
 * @author Akeed Manuideen
 */
public class FormInmateTask extends javax.swing.JFrame {

    String uNamePass;
    prisonInmate pI;
    assignmentFactory iFactory;

    /**
     * Creates new form GuardTask
     */
    public FormInmateTask() {
        initComponents();
        pI= new prisonInmate();

    }

    public FormInmateTask(String username) {
        initComponents();
        uNamePass = username;
        pI= new prisonInmate();
        iFactory=assignmentFactoryProducer.getFactory(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aTypeCombo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        descBox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        addTaskBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        inmatesTaskTable = new javax.swing.JTable();
        removeTaskBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        aTypeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Laundry", "Kitchen" }));
        aTypeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aTypeComboActionPerformed(evt);
            }
        });

        jLabel1.setText("Assignment Type");

        jLabel2.setText("Description");

        jLabel3.setText("Date");

        jXDatePicker1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXDatePicker1ActionPerformed(evt);
            }
        });

        addTaskBtn.setText("Add Task");
        addTaskBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTaskBtnActionPerformed(evt);
            }
        });

        closeBtn.setText("Close");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        inmatesTaskTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Job Type", "Description", "Date", "Username"
            }
        ));
        inmatesTaskTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inmatesTaskTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(inmatesTaskTable);
        inmatesTaskTable.getAccessibleContext().setAccessibleName("");

        removeTaskBtn.setText("Remove Task");
        removeTaskBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeTaskBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Inmate Assignment Form");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(descBox, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(aTypeCombo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addTaskBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeTaskBtn))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(176, 176, 176))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(descBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(addTaskBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(removeTaskBtn)
                            .addComponent(closeBtn))))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jXDatePicker1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXDatePicker1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jXDatePicker1ActionPerformed

    private void aTypeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aTypeComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aTypeComboActionPerformed

//    public void populateInmatesTasksTable() throws SQLException {
//
//        ArrayList<InmateAssignment> ITaskList = pI.inmatesTaskList();
//        DefaultTableModel tableModel = (DefaultTableModel) inmatesTaskTable.getModel();
//
//        //remove the contents of the table and leave the column headers        
//        for (int i = tableModel.getRowCount() - 1; i >= 0; i--) {
//            tableModel.removeRow(i);
//        }
//        //https://stackoverflow.com/questions/3879610/how-to-clear-contents-of-a-jtable
//
//        try {
//
//            Object[] row = new Object[4];
//
//            for (int i = 0; i < ITaskList.size(); i++) {
//                row[0] = ITaskList.get(i).getJobCategory();
//                row[1] = ITaskList.get(i).getJobDescription();
//                row[2] = ITaskList.get(i).getDateForDB();
//                row[3] = ITaskList.get(i).getUsername();
//                tableModel.addRow(row);
//            }
//
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//
//    }


    private void addTaskBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTaskBtnActionPerformed

        try {

            String taskType = (String) aTypeCombo.getSelectedItem();
            String description = descBox.getText();

            DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            jXDatePicker1.setFormats(dateFormat);
            DateFormat sysDate = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
            String date_to_store = sysDate.format(jXDatePicker1.getDate());
            //https://stackoverflow.com/questions/15077455/converting-date-format-of-jxdatepicker-to-date-type-of-mysql-for-storing-it-in-d
            
            Assignment assignment=iFactory.getAssignment(uNamePass, taskType, description, date_to_store);
            
            boolean success = pI.addNewInmateAssignment(assignment);
            if (success) {
                popupMessage.infoBox("A new task has been successfully added to the system", "Information");
            }
            pI.populateInmatesTasksTable(this);

        } catch (SQLException ex) {
            Logger.getLogger(FormGuardManager.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_addTaskBtnActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeBtnActionPerformed

    private void removeTaskBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeTaskBtnActionPerformed
        try {
            int i = inmatesTaskTable.getSelectedRow();

            TableModel model = inmatesTaskTable.getModel();

            String query = "DELETE FROM inmatejob where username ='" + model.getValueAt(i, 3).toString() + "' and jobDescription='" + model.getValueAt(i, 1).toString() + "'";
            https://stackoverflow.com/questions/9442027/how-to-delete-a-record-string-java-and-mysql

            pI.executeSQlQuery(query, "Deleted",this);
            pI.populateInmatesTasksTable(this);
        } catch (SQLException ex) {
            Logger.getLogger(FormGuardManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_removeTaskBtnActionPerformed

    private void inmatesTaskTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inmatesTaskTableMouseClicked

    }//GEN-LAST:event_inmatesTaskTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormInmateTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormInmateTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormInmateTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormInmateTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormInmateTask().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox aTypeCombo;
    private javax.swing.JButton addTaskBtn;
    private javax.swing.JButton closeBtn;
    private javax.swing.JTextField descBox;
    protected javax.swing.JTable inmatesTaskTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private javax.swing.JButton removeTaskBtn;
    // End of variables declaration//GEN-END:variables
}
