/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ooae2test1;

import inmatePunishments.*;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.TableModel;

public class FormInmatePunishment extends javax.swing.JFrame {

    String uNamePass;
    prisonInmate pI;

    public FormInmatePunishment() {
        initComponents();
    }

    public FormInmatePunishment(String username) {
        initComponents();
        uNamePass = username;
        pI = new prisonInmate();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pTypeCombo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        datePicker = new org.jdesktop.swingx.JXDatePicker();
        punishBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        inmatesPunishmentTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        severityCombo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pTypeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Isolation", "Starvation" }));
        pTypeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pTypeComboActionPerformed(evt);
            }
        });

        jLabel1.setText("Punishment Type");

        jLabel3.setText("Date");

        datePicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datePickerActionPerformed(evt);
            }
        });

        punishBtn.setText("PUNISH!");
        punishBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                punishBtnActionPerformed(evt);
            }
        });

        closeBtn.setText("Close");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        inmatesPunishmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Username", "Punishment Type", "Date", "Severity"
            }
        ));
        inmatesPunishmentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inmatesPunishmentTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(inmatesPunishmentTable);

        jLabel2.setText("Severity");

        severityCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Soft", "Medium", "Hard" }));
        severityCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                severityComboActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Inmate Punishment Form");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(punishBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pTypeCombo, 0, 150, Short.MAX_VALUE)
                            .addComponent(datePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(severityCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(46, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(severityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(punishBtn)
                            .addComponent(closeBtn))))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void datePickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datePickerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datePickerActionPerformed

    private void pTypeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pTypeComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pTypeComboActionPerformed

//    public void populateInmatesTasksTable() throws SQLException {
//
//        wardenMethods wM = new wardenMethods();
//        ArrayList<InmateAssignment> ITaskList = wM.inmatesTaskList();
//        DefaultTableModel tableModel = (DefaultTableModel) inmatesTaskTable.getModel();
//
//        //remove the contents of the table and leave the column headers        
//        for (int i = tableModel.getRowCount() - 1; i >= 0; i--) {
//            tableModel.removeRow(i);
//        }
//        //https://stackoverflow.com/questions/3879610/how-to-clear-contents-of-a-jtable
//
//        try {
//
//            Object[] row = new Object[4];
//
//            for (int i = 0; i < ITaskList.size(); i++) {
//                row[0] = ITaskList.get(i).getJobCategory();
//                row[1] = ITaskList.get(i).getJobDescription();
//                row[2] = ITaskList.get(i).getDateForDB();
//                row[3] = ITaskList.get(i).getUsername();
//                tableModel.addRow(row);
//            }
//
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//
//    }
//    public void setSeverityLevel(String severityType, InmatePunishmentK obj) {
//        if (severityType.equals("Soft")) {
//            obj.setpLevel(new softPunishment());
//
//        } else if (severityType.equals("Medium")) {
//            obj.setpLevel(new hardPunishment());
//        } else if (severityType.equals("Hard")) {
//            obj.setpLevel(new hardPunishment());
//        }
//        obj.punish();
//
//    }

    private void punishBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_punishBtnActionPerformed

        try {
            String taskType = (String) pTypeCombo.getSelectedItem();
            String severityType = (String) severityCombo.getSelectedItem();
            DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
            datePicker.setFormats(dateFormat);
            String date_to_store = dateFormat.format(datePicker.getDate());
            //https://stackoverflow.com/questions/15077455/converting-date-format-of-jxdatepicker-to-date-type-of-mysql-for-storing-it-in-d

            PunishmentFactory pF = new PunishmentFactory();

            InmatePunishmentK ip = pF.getPunishment(uNamePass, taskType, date_to_store, severityType);

            pI.addNewInmatePunishment(ip);

            ip.assignPunishment(uNamePass, date_to_store, severityType); 
            //calling the method to display a message regarding the punishment

            pI.populateInmatesPunishmentsTable(this);

        } catch (SQLException ex) {
            Logger.getLogger(FormInmatePunishment.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_punishBtnActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeBtnActionPerformed

    private void inmatesPunishmentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inmatesPunishmentTableMouseClicked
        int i = inmatesPunishmentTable.getSelectedRow();

        TableModel model = inmatesPunishmentTable.getModel();

        // Display Selected Row In JComboBoxes
        pTypeCombo.getModel().setSelectedItem(model.getValueAt(i, 1).toString());
//        severityCombo.getModel().setSelectedItem(model.getValueAt(i, 3).toString());

    }//GEN-LAST:event_inmatesPunishmentTableMouseClicked

    private void severityComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_severityComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_severityComboActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FormInmatePunishment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FormInmatePunishment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FormInmatePunishment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FormInmatePunishment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FormInmatePunishment().setVisible(true);
//
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBtn;
    private org.jdesktop.swingx.JXDatePicker datePicker;
    protected javax.swing.JTable inmatesPunishmentTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox pTypeCombo;
    private javax.swing.JButton punishBtn;
    private javax.swing.JComboBox severityCombo;
    // End of variables declaration//GEN-END:variables
}
