/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ooae2test1;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import notesAboutInmates.proxyNote;

public class guardHome extends javax.swing.JFrame {

    private Connection connection;
    private String guardUsername;
    prisonGuard pG = new prisonGuard();
    prisonInmate pI;
    proxyNote pN;

    /**
     * Creates new form guardHome
     */
    public guardHome(String username) {
        initComponents();
        connection = MyDatabase.getConnection();
        this.guardUsername = username;
        pI = new prisonInmate();
        this.headerLbl.setText("Welcome to your homepage, " + username + " !");

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoutBtn = new javax.swing.JButton();
        viewTasksBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tasksTable = new javax.swing.JTable();
        populateInmateBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        addNoteBtn = new javax.swing.JButton();
        notetxtBox = new javax.swing.JTextField();
        headerLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        viewTasksBtn.setText("View Tasks");
        viewTasksBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTasksBtnActionPerformed(evt);
            }
        });

        tasksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Task Type", "Description", "Date"
            }
        ));
        jScrollPane3.setViewportView(tasksTable);

        populateInmateBtn.setText("Select Inmate");
        populateInmateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                populateInmateBtnActionPerformed(evt);
            }
        });

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        addNoteBtn.setText("ADD NOTE");
        addNoteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNoteBtnActionPerformed(evt);
            }
        });

        headerLbl.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        headerLbl.setText("Welcome to your homepage, //username here");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3)
                            .addComponent(viewTasksBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(headerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(populateInmateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(notetxtBox)
                    .addComponent(addNoteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(headerLbl)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(viewTasksBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(populateInmateBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(notetxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addNoteBtn)))
                .addGap(10, 10, 10)
                .addComponent(logoutBtn)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        try {
            java.awt.Window win[] = java.awt.Window.getWindows();
            for (int i = 0; i < win.length; i++) {
                win[i].dispose();
                win[i] = null;
            }
            wardenMethods wardenActs = new wardenMethods();
            loginForm newLogin = new loginForm();
            newLogin.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(guardHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void viewTasksBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTasksBtnActionPerformed
        try {
            this.populateTasksTable();
        } catch (SQLException ex) {
            Logger.getLogger(guardHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_viewTasksBtnActionPerformed

    private void populateInmateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_populateInmateBtnActionPerformed
        try {
            ArrayList<prisonInmate> inmateList = pI.inmateList();
            jList1.setModel(new DefaultListModel()); //https://stackoverflow.com/questions/10375115/jlist-getmodel-classcastexception
            DefaultListModel listModel = (DefaultListModel) jList1.getModel();

            for (prisonInmate inmateList1 : inmateList) {

                listModel.addElement(inmateList1.getUsername()); //https://docs.oracle.com/javase/tutorial/uiswing/components/list.html

            }
        } catch (SQLException ex) {
            Logger.getLogger(guardHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_populateInmateBtnActionPerformed

    private void addNoteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNoteBtnActionPerformed
        try {
            String noteToinsert = notetxtBox.getText();
            String uNameOfInmate = jList1.getSelectedValue().toString();

            pN = new proxyNote();
            pN.makeNote(noteToinsert, uNameOfInmate, guardUsername);

        } catch (Exception ex) {
            Logger.getLogger(guardHome.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_addNoteBtnActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged

    }//GEN-LAST:event_jList1ValueChanged

    public void populateTasksTable() throws SQLException {

        ArrayList<GuardAssignment> individualGuardTaskList = pG.individualGuardTaskList(guardUsername);
        DefaultTableModel tableModel = (DefaultTableModel) tasksTable.getModel();

        //remove the contents of the table and leave the column headers        
        for (int i = tableModel.getRowCount() - 1; i >= 0; i--) {
            tableModel.removeRow(i);
        }
        //https://stackoverflow.com/questions/3879610/how-to-clear-contents-of-a-jtable

        try {

            Object[] row = new Object[3];

            for (int i = 0; i < individualGuardTaskList.size(); i++) {
                row[0] = individualGuardTaskList.get(i).getTaskType();
                row[1] = individualGuardTaskList.get(i).getDescription();
                row[2] = individualGuardTaskList.get(i).getDateForDB();

                tableModel.addRow(row);
            }

        } catch (Exception e) {
        }

    }

//    public void populateMessagesTable() throws SQLException {
//
//        ArrayList<GuardMessage> individualGuardMessageList = pG.individualGuardMessageList(guardUsername);
//        DefaultTableModel tableModel = (DefaultTableModel) notifTable.getModel();
//
//        //remove the contents of the table and leave the column headers        
//        for (int i = tableModel.getRowCount() - 1; i >= 0; i--) {
//            tableModel.removeRow(i);
//        }
//        //https://stackoverflow.com/questions/3879610/how-to-clear-contents-of-a-jtable
//
//        try {
//
//            Object[] row = new Object[2];
//
//            for (int i = 0; i < individualGuardMessageList.size(); i++) {
//                row[0] = individualGuardMessageList.get(i).getDescription();                
//                row[1] = individualGuardMessageList.get(i).getDateForDB();
//
//                tableModel.addRow(row);
//            }
//
//        } catch (Exception e) {
//        }
//
//    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(guardHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(guardHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(guardHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(guardHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new guardHome().setVisible(true);
//
//            }
//
//        });
//
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNoteBtn;
    private javax.swing.JLabel headerLbl;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JTextField notetxtBox;
    private javax.swing.JButton populateInmateBtn;
    private javax.swing.JTable tasksTable;
    private javax.swing.JButton viewTasksBtn;
    // End of variables declaration//GEN-END:variables
}
